spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ser
    username: root
    password: 120512zxc@
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        logging.level:
          org.hibernate.SQL: debug
        #  org.hibernate.type: trace

