spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ser
    username: root
    password: 120512zxc@
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
        logging.level:
          org.hibernate.SQL: debug
        #  org.hibernate.type: trace

